SELECT * FROM MATERIAL;
SELECT * FROM MATERIAL ORDER BY DESCRIPCION;
SELECT * FROM MATERIAL WHERE DESCRIPCION LIKE '%ELEC%' ORDER BY DESCRIPCION;
SELECT IMAGEN, NOMBREIMAGEN FROM MATERIAL WHERE CODIGO='150015';

INSERT INTO MATERIAL VALUES ('150015', 'ABRAZ FºGº SIMPLE P/PAST 1''Ø,125mmØPOS','UND',SELECT MAX(IDIMAGEN)+1 FROM IMAGENES);

SELECT * FROM IMAGENES;
SELECT MAX(IDIMAGEN)+1 FROM IMAGENES;

DELETE FROM IMAGENES WHERE IDIMAGEN=6;