SELECT * FROM MATERIAL;
SELECT * FROM MATERIAL ORDER BY DESCRIPCION;
SELECT * FROM MATERIAL WHERE DESCRIPCION = 'ABRAZ FºGº DOB P/PAST 2"Ø,140mmØPOS';
SELECT * FROM MATERIAL WHERE DESCRIPCION LIKE '%ELEC%' ORDER BY DESCRIPCION;
SELECT IMAGEN, NOMBREIMAGEN FROM MATERIAL WHERE CODIGO='150015';

INSERT INTO MATERIAL VALUES ('150015', 'ABRAZ FºGº SIMPLE P/PAST 1''Ø,125mmØPOS','UND',SELECT MAX(IDIMAGEN)+1 FROM IMAGENES);

UPDATE MATERIAL SET DESCRIPCION = REPLACE(DESCRIPCION, "foo", "bar");

SELECT * FROM IMAGENES;
SELECT MAX(IDIMAGEN)+1 FROM IMAGENES;

DELETE FROM MATERIAL;

SELECT * FROM hoja1$;
INSERT INTO MATERIAL (CODIGO, DESCRIPCION, UNIDAD) SELECT hoja1$.`Código`, hoja1$.`Descripción`, hoja1$.`Unid` FROM hoja1$;

DELETE FROM IMAGENES;
DELETE FROM IMAGENES WHERE IDIMAGEN=6;