SELECT * FROM PUNTO;
SELECT MAX(CODIGO) FROM PUNTO;
SELECT PUNTO FROM PUNTO WHERE CODIGOFLC='F12-03-27' ORDER BY PUNTO ASC;

SELECT CODIGO FROM PUNTO WHERE PUNTO='P1' AND CODIGOFLC='F12-03-27';

DELETE FROM PUNTO;
DELETE FROM PUNTO WHERE PUNTO='P4' AND CODIGOFLC='F12-03-27';