SELECT * FROM PUNTO_SERVICIO;

SELECT PS.CODIGOSERVICIO, PS.CANTIDAD FROM PUNTO_SERVICIO PS INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE CODIGOPUNTO='P100000001' AND P.CODIGOFLC='F12-03-27';

SELECT DISTINCT P.PUNTO, ps.codigopunto FROM PUNTO_SERVICIO PS INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE P.CODIGOFLC='F12-03-27';

SELECT PS.CODIGOSERVICIO, S.DESCRIPCION, S.UNIDAD, PS.CANTIDAD FROM PUNTO_SERVICIO PS INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO WHERE CODIGOPUNTO='P100000002';

SELECT S.CODIGO, S.DESCRIPCION, S.UNIDAD FROM PUNTO_SERVICIO PS INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO WHERE CODIGOPUNTO='P100000001';

SELECT S.CODIGO, S.DESCRIPCION, S.UNIDAD, PS.CANTIDAD FROM PUNTO_SERVICIO PS INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE P.PUNTO='P1';

SELECT PS.CODIGOSERVICIO FROM PUNTO_SERVICIO PS INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE P.PUNTO='P1';

UPDATE PUNTO_SERVICIO SET CANTIDAD='1' WHERE CODIGOPUNTO=(SELECT CODIGO FROM PUNTO WHERE PUNTO='P1' AND CODIGOSERVICIO='300527');

INSERT INTO PUNTO_SERVICIO VALUES( (SELECT CODIGO FROM PUNTO WHERE PUNTO='P1' AND CODIGOFLC='F12-03-27') ,'300554','1');

SELECT @rownum:=@rownum+1 AS rownum, S.`DESCRIPCION`, P.`PUNTO`, PS.CANTIDAD FROM (SELECT @rownum:=0) r, PUNTO_SERVICIO PS INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.`CODIGO` INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE P.CODIGOFLC='F12-03-27';

SELECT @rownum:=@rownum+1 AS rownum FROM (SELECT @rownum:=0) r WHERE @rownum<5;

SELECT DISTINCT PS.CODIGOSERVICIO, S.DESCRIPCION, S.`UNIDAD` FROM PUNTO_SERVICIO PS INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO WHERE P.CODIGOFLC='F12-03-27';
SELECT COUNT(*) FROM PUNTO_SERVICIO PS INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO WHERE P.CODIGOFLC='F12-03-27';

SET @numero=0;
SELECT @numero:=@numero+1 FROM `punto_servicio` WHERE @numero<((SELECT COUNT(*) FROM `punto_servicio`)-5);

SELECT COUNT(*) FROM `punto_servicio` PS INNER JOIN `punto` P ON PS.`CODIGOPUNTO`=P.`CODIGO` WHERE P.`CODIGOFLC`='F12-03-27';

SELECT COUNT(*) FROM `punto_servicio` WHERE `CODIGOSERVICIO` IN (
SELECT DISTINCT `CODIGOSERVICIO`
FROM `punto_servicio`
);

SELECT DISTINCT S.CODIGO, S.DESCRIPCION, S.`UNIDAD`, @rownum:=@rownum+1 AS ITEM  
FROM (SELECT @rownum:=0) r, PUNTO_SERVICIO PS 
INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO 
INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO 
WHERE P.CODIGOFLC='F12-03-27' GROUP BY S.CODIGO;

SELECT * FROM PUNTO_SERVICIO PS 
INNER JOIN PUNTO P ON PS.`CODIGOPUNTO`=P.`CODIGO`
WHERE P.`CODIGOFLC`='F12-03-27';

SELECT DISTINCT PS.`CODIGOSERVICIO`, @rownum:=@rownum+1 ‘nro’
FROM `punto_servicio` PS, (SELECT @rownum:=0) r
INNER JOIN PUNTO P ON PS.`CODIGOPUNTO`=P.`CODIGO`
WHERE P.`CODIGOFLC`='F12-03-27'
GROUP BY PS.`CODIGOSERVICIO`;