SELECT DISTINCT P.PUNTO, ps.codigopunto FROM PUNTO_SERVICIO PS INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE P.CODIGOFLC='F12-03-25';
SELECT PS.CODIGOSERVICIO, S.DESCRIPCION, S.UNIDAD, PS.CANTIDAD FROM PUNTO_SERVICIO PS INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO WHERE CODIGOPUNTO='P100000002';
SELECT S.CODIGO, S.DESCRIPCION, S.UNIDAD FROM PUNTO_SERVICIO PS INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO WHERE CODIGOPUNTO='P100000001';
SELECT S.CODIGO, S.DESCRIPCION, S.UNIDAD, PS.CANTIDAD FROM PUNTO_SERVICIO PS INNER JOIN SERVICIO S ON PS.CODIGOSERVICIO=S.CODIGO INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE P.PUNTO='P1';
SELECT PS.CODIGOSERVICIO FROM PUNTO_SERVICIO PS INNER JOIN PUNTO P ON PS.CODIGOPUNTO=P.CODIGO WHERE P.PUNTO='P1';

UPDATE PUNTO_SERVICIO SET CANTIDAD='1' WHERE CODIGOPUNTO=(SELECT CODIGO FROM PUNTO WHERE PUNTO='P1' AND CODIGOSERVICIO='300527');